
{% set version = environ.get('GIT_DESCRIBE_TAG').lstrip('v') %}
{% set number = GIT_DESCRIBE_NUMBER %}

package:
  name: titan-arrow-pkg
  version: {{ version }}

build:
  number: {{ number }}

about:
  home: https://github.com/gottingen/titan-arrow
  license: Apache License 2
  license_family: APACHE
  license_file: LICENSE
  summary: A library for c++ based libraries and rpc libraries

source:
  git_url: ../

outputs:
  - name: tarrow
    script: bld.sh   # [not win]
    script: bld.bat  # [win]
    build:
      string: "h{{ GIT_DESCRIBE_HASH }}_{{ number }}"
      run_exports:
        - {{ pin_compatible('tarrow', exact=True) }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - sysroot_linux-64 >=2.17  # [linux64]
      host:
        - sysroot_linux-64 >=2.17  # [linux64]
      run:
        - sysroot_linux-64 >=2.17  # [linux64]
    test:
      commands:
        - test -f $PREFIX/lib/libarrow.so              # [linux]
        - test -f $PREFIX/lib/libarrow.dylib           # [osx]
      #  - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
      #  - conda inspect objects -p $PREFIX $PKG_NAME   # [osx]
